### ISSUE TITLE
publish to pypi

### ISSUE THREAD

**Issue by HBehrens** [HBehrens/puncover#34]
Simplify usage by publishing to pypi as suggested by @carlescufi [at the zephyr project](https://github.com/zephyrproject-rtos/zephyr/pull/23695#discussion_r419384687). May require some thought around versioning.

**Comment by tyhoff** [comment]
I'm curious why you think versioning requires more thought than slapping a version on it? 

I'm also happy to take this task on, I now have a decent workflow for doing this from publishing all the gdbundle plugins.

**Comment by HBehrens** [comment]
Oh wow, thank you @tyhoff help or sharing best practices/recommendations would be much appreciated! I've only ever [published a package once](https://pypi.org/project/eachpng/) and that's been a while.

I am not sure about the version, it was simply something to consider once you go "public", I guess. `puncover/version.py` currently says `0.0.1`, that's probably "safe" to go with? Or would the workflow you had in mind generate a version number (e.g. `.patch` component) automatically?

`setup.py` in this repo seems to be almost ready once you use twine. At the very least, I wanted to do some testing on macOS and Linux though. And a really nice feature to have would be automatic publishing (e.g. whenever travis detects a version tag associated with the commit).

What did you have in mind? Which user would you publish this with? Would `hbehrens` be a good choice? If so and if you are willing to put in the work, do you want me to upload an API token as a secret (travis)?

**Comment by carlescufi** [comment]
@HBehrens 

A couple of quick comments based on my own experience with pypi.

> I am not sure about the version, it was simply something to consider once you go "public", I guess. `puncover/version.py` currently says `0.0.1`, that's probably "safe" to go with? Or would the workflow you had in mind generate a version number (e.g. `.patch` component) automatically?

I would recommend starting with a low number, something like 0.1.0, and go from there. There is no tricks or secrets to publish a package to pypi, it is trivial in itself.

> `setup.py` in this repo seems to be almost ready once you use twine. At the very least, I wanted to do some testing on macOS and Linux though. And a really nice feature to have would be automatic publishing (e.g. whenever travis detects a version tag associated with the commit).

We don't have automatic publishing for much bigger projects than this one, so to be honest I think you can defer that and just run `twine` manually every time you cut a release. What does help is having a suite of tests that are run every time you post a PR, so that when you post the one that increases the version number you are more or less confident that the code is not broken. You can take a quick look at how it's done in Zephyr's west using `tox`:
https://github.com/zephyrproject-rtos/west/tree/master/tests

> What did you have in mind? Which user would you publish this with? Would `hbehrens` be a good choice? If so and if you are willing to put in the work, do you want me to upload an API token as a secret (travis)?

There are two ways you can go about this. My recommendation would be to have either a company or project-wide account that you share credentials with through something like LastPass, this is what we do in Zephyr and also at Nordic. The other option is to have your own account, and then you can actually add other pypi accounts to your own and give them permissions to publish new versions.

**Comment by HBehrens** [comment]
Thank you two for your recommendations. @tyhoff already went ahead and integrated tox into the build with #35. I believe I will continue with manually publishing using my personal PyPI account for the time being after that landed, then.

**Comment by noahp** [comment]
`puncover` is now published to PyPI :tada: https://pypi.org/project/puncover/
