### ISSUE TITLE
Downloading the entire site for viewing later or sending

### ISSUE THREAD

**Issue by EarthLord** [HBehrens/puncover#45]
Heiko, Thanks a lot for the wonderful tool. Would it be possible to save the entire website a particular build ?
Asking this for 1. sharing with anyone else 2. viewing later 3. comparing with build with another configuration.

**Comment by HBehrens** [comment]
One of the early versions of pucover did in fact generate static pages to produce an "offline" version but I discarded this approach due to amount of time it took for more complex projects and an increasing amount of features (resulting in an unmanageable amount of pages). I believe a (partial) rewrite that pushes at least some of the logic into the client would be a feasible approach for 1 and 2.

"Viewing later" 2 could possibly be done by persisting and reloading the in-memory model after the parsing step.

For comparing versions 3, I usually run two instances of puncover in parallel on different ports but would also love to have specific views that highlight the deltas.

At the moment, I don't have the capacity to do any major work on puncover myself, I am afraid.

**Comment by EarthLord** [comment]
Thanks for the quick reply Heiko. Can you please let me know how to run puncover in parallel on different ports?

**Comment by HBehrens** [comment]
You can set the port explicitly using the `--port` argument (defaults to 5000)
```
puncover <any_other_args> --elf build_1/binary.elf --port 5000
```
and launch another instance for another elf
```
puncover <any_other_args> --elf build_2/binary.elf --port 5001
```
Note that you will have to make a copy of your elf (or entire build folder if you are taking advantage of that stack usage analysis) manually. I indicated this here with two different build folders `build_1` and `build_2`.
